### ISSUE TITLE
add a demo page

### ISSUE THREAD

**Issue by kamikaz1k** [slyapustin/django-classified#57]
hi, I am interested in checking out this project, but the readme didn't have any links to any demo pages. This discouraged me from checking it out.

Just thought I'd mention it, incase the maintainers would like to add a demo app to the readme so people can check it out without running it locally.

**Comment by slyapustin** [comment]
@kamikaz1k There is a link to the `django-classified-demo` project:
https://github.com/slyapustin/django-classified-demo

Hope this helps.
